<html>
    <head>
        <title></title>
    </head>
    <body>
        <div class="column info">
            <p class="name">CS35</p>
            <p class="subname">Компактный, стильный и экономичный</p>
            <p>кроссовер на все случаи жизни</p>
            <p class="price">
                от 123 9600 323 Р
                <span class="das"> вфывфывфы</span>
            </p>
            <a href="/credit" data-brand="25" data-model="103" data-pack="1084" class="btn black post_request">
                Купить в кредит
            </a>
        </div>
    </body>
</html>