<!DOCTYPE html>
<html>
    <head>
        <?php echo $this->fetch('head.phtml'); ?>
    </head>
    <body>
        <?php echo $this->fetch('navbar.phtml'); ?>

        <div class="container-fluid">
            <legend><h1>Список городов</h1></legend>

            <div class="row">
                <div class="col-md-12">
                    <button type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal">
                        <i class="fas fa-plus"></i>
                         Добавить город
                    </button>
                </div>
            </div>

            <br/>

            <div class="row">
                <div class="col-md-12">
                    <ul>
                        <?php foreach($city as $item) { ?>
                            <li>
                                <?php echo $item['name']; ?>
                                <a href="/city/remove/<?php echo $item['id']; ?>">
                                    <i class="far fa-trash-alt"></i>
                                </a>
                            </li>  
                        <?php } ?>
                    </ul>
                </div>               
            </div>

        </div>

        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog modal-sm" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Добавить город</h4>
                    </div>
                    <div class="modal-body">
                        <form method="POST" action="/city/add">
                            <div class="form-group">
                                <label>Название города</label>
                                <input type="text" name="city" class="form-control" required>
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Добавить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <?php echo $this->fetch('footer.phtml'); ?>
    </body>
</html>
