<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">
                JustWe.Price <?php echo $this->getAttribute('version'); ?>
            </a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <div class="nav navbar-right">
            </div>  

            <ul class="nav navbar-nav navbar-right">
                <li><a href="/"><i class="fas fa-dollar-sign"></i> Цены</a></li>
                <li><a href="/city"><i class="fas fa-globe"></i> Города</a></li>
                <li><a href="/cars"><i class="fas fa-car"></i> Автомобили</a></li>
                <li><a href="/shop"><i class="fas fa-shopping-cart"></i> Автосалоны</a></li>
                <li><a href="/logout"><i class="fas fa-sign-out-alt"></i> Выход</a></li>
            </ul>
        </div>
    </div>
</nav>
