<!DOCTYPE html>
<html>
<head>
    <?php echo $this->fetch('head.phtml'); ?>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            <h1>
                На сайте ведутся технические работы :( <br>
                <small>Зайдите позднее...</small>
            </h1>
        </div>
    </div>
</div>

<?php echo $this->fetch('footer.phtml'); ?>
</body>
</html>
