<style type="text/css">
    .outer-container {
        width: 100%;
        height: 70vh;
    }

    .inner-container {
        height: 100%;
        overflow: hidden;
    }

    .table-header {
        position: relative;
    }

    .table-header tr th {
        height: 40px;
    }

    .table-body {
        overflow: auto;
    }

    .table-body tr td {
        border-top: 1px solid #ddd;
    }

    .table-body tr td, .table-header tr th {
        text-align: left;
        padding: 8px;
        width:120px;
        min-width: 120px;  
        box-sizing: border-box;        
    }    

    .table-body tr:nth-of-type(odd) {
        background-color: #f9f9f9;
    }

    .table-body tr:hover {
        background-color: #f5f5f5;
    }
</style>

<div class="outer-container">
    <div class="inner-container">
        <div class="table-header">
            <table>
                <thead>
                    <tr>
                        <th>Марка</th>
                        <th>Модель</th>
                        <?php foreach($shop as $value) { ?>
                            <th>
                                <?php echo $value['name']; ?>
                                <a href="#"
                                   data-toggle="modal"
                                   data-target="#modal-refresh-price"
                                   data-shop-id="<?php echo $value['shop_id']; ?>"
                                   data-shop-name="<?php echo $value['name']; ?>"
                                >
                                    <i class="fas fa-sync-alt"
                                       data-toggle="tooltip"
                                       data-placement="bottom"
                                       title="Обновить цены на столбец '<?php echo $value['name'] ?>'"
                                    ></i>
                                </a>
                            </th>
                        <?php } ?>                        
                    </tr>
                </thead>
            </table>
        </div>
        <div class="table-body">
            <table>
                <tbody>
                    <?php foreach ($data as $key => $value) { ?>
                        <tr>
                            <td><?php echo $value['mark_name']; ?></td>
                            <td><?php echo $value['model_name']; ?></td>

                            <?php foreach($value['shop'] as $value) { ?>
                                <?php if( isset($value['price']) ) { ?>
                                    <?php if( !empty($value['price']['price']) AND $value['price']['price'] != 0 ) { ?>
                                        <td style="background-color: #abffab;">
                                            <div class="price-item">
                                                <a href="#" 
                                                data-url="<?php echo $value['price']['url']; ?>" 
                                                data-parent-template="<?php echo $value['price']['parent_template']; ?>"
                                                data-template="<?php echo $value['price']['template']; ?>" 
                                                data-id="<?php echo $value['price']['id']; ?>" 
                                                data-toggle="modal" 
                                                data-target="#myModal2"
                                                data-remove-url="/price/remove/<?php echo $value['price']['id']; ?>"
                                                >
                                                    <?php echo number_format($value['price']['price'], 0, '', ' '); ?>
                                                </a>
                                                <span class="updated-at">
                                                    <small><?php echo substr( $value['price']['updated_at'], 0, strpos($value['price']['updated_at'], ' ') ); ?></small>
                                                </span>
                                            </div>
                                        </td>           
                                    <?php } else { ?>
                                        <td style="background-color: #fbd736;">
                                            <div class="price-item">
                                                <a href="#" 
                                                data-url="<?php echo $value['price']['url']; ?>" 
                                                data-parent-template="<?php echo $value['price']['parent_template']; ?>"
                                                data-template="<?php echo $value['price']['template']; ?>" 
                                                data-id="<?php echo $value['price']['id']; ?>" 
                                                data-toggle="modal" 
                                                data-target="#myModal2"
                                                data-remove-url="/price/remove/<?php echo $value['price']['id']; ?>"
                                                >
                                                    Нет данных
                                                </a>
                                            </div>
                                        </td>
                                    <?php } ?>
                                <?php } else { ?>
                                    <td>
                                        <div class="price-item">
                                            -
                                        </div>
                                    </td>
                                <?php } ?>
                            <?php } ?>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="modal fade" id="modal-refresh-price" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">
                    Пакетное обновление цен для автосалона <span class="js-shop-name"></span>
                </h4>
            </div>
            <div class="modal-body">
                <textarea class="form-control" style="resize: none; width: 100%; height: 250px;"></textarea>

                <br/>

                <button class="btn btn-success js-start-refresh" data-shop-name="" data-shop-id="">
                    <i class="fas fa-play"></i>
                    Начать
                </button>
                <button class="btn btn-danger js-stop-refresh" disabled>
                    <i class="far fa-stop-circle"></i>
                    Стоп
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    (function() {
        $('#modal-refresh-price').on('shown.bs.modal', function (event) {
            var a = $(event.relatedTarget);

            var name = a.data('shop-name');
            var id = a.data('shop-id');

            $(this).find('.js-start-refresh').attr('data-shop-name', name);
            $(this).find('.js-start-refresh').attr('data-shop-id', id);

            $(this).find('.js-start-refresh').attr('disabled', false);
            $(this).find('.js-stop-refresh').attr('disabled', true);
        });

        $('#modal-refresh-price textarea').keydown(function() {
            event.preventDefault();
        });

        $('.js-start-refresh').click(function() {
            $(this).attr('disabled', true);
            $('.js-stop-refresh').attr('disabled', false);

            var id = $(this).data('shop-id');

            $.post({
                method: 'POST',
                url: '/price/get',
                data: {
                    shop_id : id
                },
                dataType: 'json',

                success: function(data) {
                    for(var key in data) {
                        $.post({
                            method: 'POST',
                            url: '/price/refresh',
                            data: {
                                id: data[key].id
                            },
                            timeout: 3000,

                            error: function() {
                                $('#modal-refresh-price textarea').append("Ошибка обновления цены для автомобиля " + data[key].url + "\n");
                            },

                            success: function() {
                                $('#modal-refresh-price textarea').append("Успешное обновление цены для автомобиля " + data[key].url + "\n");
                            }
                        });

                        break;
                    }
                }
            });
        });

        $('.js-stop-refresh').click(function() {

        });
    })();

    (function() {
        $('[data-toggle="tooltip"]').tooltip();
        
        $(document).ready(function () {
            setTableBody();
            $(window).resize(setTableBody);

            $(".table-body").scroll(function () {
                $(".table-header").offset({ 
                    left: -1*this.scrollLeft+15
                });
            });
        });

        function setTableBody() {
            $(".table-body").height( $(".inner-container").height() - $(".table-header").height() );
        }
    })();
</script>